version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: app
    ports:
      - "5432:5432"