version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: app           # User 'app'
      POSTGRES_PASSWORD: app_pass  # Password for user 'app'
      POSTGRES_DB: app_db         # Default database to create
    ports:
      - "5433:5432"               # Expose PostgreSQL port 5432